import { Inject, Injectable, Logger, Optional } from '@nestjs/common';
import {
  AuditLogRecord,
  AuditModuleOptions,
  AuditQueryOptions,
  AuditQueryResult,
  ExportOptions,
  ExportResult,
  LogActionDto,
} from './types.js';
import { redactSensitive } from './diff.js';

// The token under which the host app's PrismaService is registered.
export const PRISMA_SERVICE_TOKEN = 'PrismaService';
export const AUDIT_MODULE_OPTIONS = 'AUDIT_MODULE_OPTIONS';

// Minimal interface so we don't import @prisma/client directly (avoids version coupling).
interface PrismaAuditClient {
  auditLog: {
    create(args: { data: Record<string, unknown> }): Promise<AuditLogRecord>;
    findMany(args: Record<string, unknown>): Promise<AuditLogRecord[]>;
    count(args: Record<string, unknown>): Promise<number>;
  };
}

@Injectable()
export class AuditService {
  private readonly logger = new Logger(AuditService.name);
  private readonly maxQueryLimit: number;
  private readonly logFailures: boolean;
  private readonly resourcePrefix: string | undefined;

  constructor(
    @Inject(PRISMA_SERVICE_TOKEN) private readonly prisma: PrismaAuditClient,
    @Optional()
    @Inject(AUDIT_MODULE_OPTIONS)
    private readonly options: AuditModuleOptions = {},
  ) {
    this.maxQueryLimit = options.maxQueryLimit ?? 500;
    this.logFailures = options.logFailures ?? true;
    this.resourcePrefix = options.resourcePrefix;
  }

  // ─── Write ───────────────────────────────────────────────────────────────────

  /**
   * Persist an audit log entry.
   * Always resolves — exceptions are swallowed and logged to avoid disrupting
   * the calling request when audit storage fails.
   */
  async log(dto: LogActionDto): Promise<AuditLogRecord | null> {
    if (!this.logFailures && dto.success === false) {
      return null;
    }

    const resource = this.resourcePrefix
      ? `${this.resourcePrefix}/${dto.resource}`
      : dto.resource;

    const before = dto.before ? redactSensitive(dto.before as Record<string, unknown>) : null;
    const after = dto.after ? redactSensitive(dto.after as Record<string, unknown>) : null;

    try {
      return await this.prisma.auditLog.create({
        data: {
          userId: dto.userId ?? null,
          userEmail: dto.userEmail ?? null,
          action: dto.action,
          resource,
          resourceId: dto.resourceId ?? null,
          before,
          after,
          ip: dto.ip ?? null,
          userAgent: dto.userAgent ?? null,
          httpRoute: dto.httpRoute ?? null,
          metadata: dto.metadata ?? null,
          success: dto.success ?? true,
          error: dto.error ?? null,
        },
      });
    } catch (err) {
      this.logger.error('Failed to write audit log entry', err);
      return null;
    }
  }

  // ─── Read ─────────────────────────────────────────────────────────────────────

  /**
   * Query audit logs with filters, pagination and sorting.
   */
  async query(options: AuditQueryOptions = {}): Promise<AuditQueryResult> {
    const {
      filters = {},
      page = 1,
      orderBy = 'timestamp',
      orderDir = 'desc',
    } = options;

    const limit = Math.min(options.limit ?? 50, this.maxQueryLimit);
    const skip = (Math.max(page, 1) - 1) * limit;

    const where = this.buildWhereClause(filters);

    const [data, total] = await Promise.all([
      this.prisma.auditLog.findMany({
        where,
        orderBy: { [orderBy]: orderDir },
        skip,
        take: limit,
      }),
      this.prisma.auditLog.count({ where }),
    ]);

    return {
      data,
      total,
      page: Math.max(page, 1),
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  /**
   * Convenience: fetch all logs for a specific resource record.
   */
  async findByResource(resource: string, resourceId: string): Promise<AuditLogRecord[]> {
    const res = await this.query({
      filters: { resource, resourceId },
      limit: this.maxQueryLimit,
      orderBy: 'timestamp',
      orderDir: 'desc',
    });
    return res.data;
  }

  /**
   * Convenience: fetch all logs generated by a specific user.
   */
  async findByUser(userId: string, page = 1, limit = 50): Promise<AuditQueryResult> {
    return this.query({ filters: { userId }, page, limit });
  }

  // ─── Export ───────────────────────────────────────────────────────────────────

  /**
   * Export audit logs as JSON or CSV.
   */
  async export(opts: ExportOptions): Promise<ExportResult> {
    const maxRows = opts.maxRows ?? 10_000;
    const result = await this.query({
      filters: opts.filters,
      limit: Math.min(maxRows, this.maxQueryLimit * 20),
      page: 1,
      orderBy: 'timestamp',
      orderDir: 'desc',
    });

    const generatedAt = new Date();

    if (opts.format === 'json') {
      return {
        format: 'json',
        content: JSON.stringify(result.data, null, 2),
        rowCount: result.data.length,
        generatedAt,
      };
    }

    // CSV
    const content = toCsv(result.data);
    return {
      format: 'csv',
      content,
      rowCount: result.data.length,
      generatedAt,
    };
  }

  // ─── Private helpers ──────────────────────────────────────────────────────────

  private buildWhereClause(filters: AuditQueryOptions['filters'] = {}): Record<string, unknown> {
    const where: Record<string, unknown> = {};

    if (filters.userId) where['userId'] = filters.userId;
    if (filters.userEmail) where['userEmail'] = { contains: filters.userEmail, mode: 'insensitive' };
    if (filters.resourceId) where['resourceId'] = filters.resourceId;
    if (typeof filters.success === 'boolean') where['success'] = filters.success;

    if (filters.action) {
      where['action'] = Array.isArray(filters.action)
        ? { in: filters.action }
        : filters.action;
    }

    if (filters.resource) {
      where['resource'] = Array.isArray(filters.resource)
        ? { in: filters.resource }
        : filters.resource;
    }

    if (filters.from || filters.to) {
      where['timestamp'] = {
        ...(filters.from ? { gte: new Date(filters.from) } : {}),
        ...(filters.to ? { lte: new Date(filters.to) } : {}),
      };
    }

    if (filters.search) {
      const s = filters.search;
      where['OR'] = [
        { userEmail: { contains: s, mode: 'insensitive' } },
        { resource: { contains: s, mode: 'insensitive' } },
        { resourceId: { contains: s, mode: 'insensitive' } },
        { httpRoute: { contains: s, mode: 'insensitive' } },
        { action: { contains: s, mode: 'insensitive' } },
      ];
    }

    return where;
  }
}

// ─── CSV serialiser ───────────────────────────────────────────────────────────

const CSV_COLUMNS: Array<keyof AuditLogRecord> = [
  'id', 'timestamp', 'userId', 'userEmail',
  'action', 'resource', 'resourceId',
  'ip', 'userAgent', 'httpRoute',
  'success', 'error',
];

function toCsv(rows: AuditLogRecord[]): string {
  const escape = (v: unknown): string => {
    if (v === null || v === undefined) return '';
    const s = typeof v === 'object' ? JSON.stringify(v) : String(v);
    // Wrap in quotes if the value contains comma, quote, or newline
    if (/[",\n\r]/.test(s)) {
      return `"${s.replace(/"/g, '""')}"`;
    }
    return s;
  };

  const header = CSV_COLUMNS.join(',');
  const lines = rows.map((row) =>
    CSV_COLUMNS.map((col) => escape(row[col])).join(','),
  );

  return [header, ...lines].join('\n');
}
